//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ddc/message/DummyData.msg.
//

#ifndef __INET_DUMMYDATA_M_H
#define __INET_DUMMYDATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class DummyData;

}  // namespace inet


namespace inet {

/**
 * Class generated from <tt>ddc/message/DummyData.msg:10</tt> by opp_msgtool.
 * <pre>
 * packet DummyData
 * {
 *     int dummy_data;
 * }
 * </pre>
 */
class DummyData : public ::omnetpp::cPacket
{
  protected:
    int dummy_data = 0;

  private:
    void copy(const DummyData& other);

  protected:
    bool operator==(const DummyData&) = delete;

  public:
    DummyData(const char *name=nullptr, short kind=0);
    DummyData(const DummyData& other);
    virtual ~DummyData();
    DummyData& operator=(const DummyData& other);
    virtual DummyData *dup() const override {return new DummyData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDummy_data() const;
    virtual void setDummy_data(int dummy_data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DummyData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DummyData& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DummyData *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DummyData*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DUMMYDATA_M_H

