//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ddc/message/RequestNodeInformation.msg.
//

#ifndef __INET_REQUESTNODEINFORMATION_M_H
#define __INET_REQUESTNODEINFORMATION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class RequestNodeInformation;

}  // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

/**
 * Class generated from <tt>ddc/message/RequestNodeInformation.msg:13</tt> by opp_msgtool.
 * <pre>
 * class RequestNodeInformation extends inet::Packet
 * {
 * }
 * </pre>
 */
class RequestNodeInformation : public ::inet::Packet
{
  protected:

  private:
    void copy(const RequestNodeInformation& other);

  protected:
    bool operator==(const RequestNodeInformation&) = delete;

  public:
    RequestNodeInformation(const char *name=nullptr);
    RequestNodeInformation(const RequestNodeInformation& other);
    virtual ~RequestNodeInformation();
    RequestNodeInformation& operator=(const RequestNodeInformation& other);
    virtual RequestNodeInformation *dup() const override {return new RequestNodeInformation(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RequestNodeInformation& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RequestNodeInformation& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::RequestNodeInformation *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::RequestNodeInformation*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_REQUESTNODEINFORMATION_M_H

