//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ddc/message/Reset.msg.
//

#ifndef __INET_RESET_M_H
#define __INET_RESET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class Reset;

}  // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

/**
 * Class generated from <tt>ddc/message/Reset.msg:13</tt> by opp_msgtool.
 * <pre>
 * class Reset extends inet::Packet
 * {
 * }
 * </pre>
 */
class Reset : public ::inet::Packet
{
  protected:

  private:
    void copy(const Reset& other);

  protected:
    bool operator==(const Reset&) = delete;

  public:
    Reset(const char *name=nullptr);
    Reset(const Reset& other);
    virtual ~Reset();
    Reset& operator=(const Reset& other);
    virtual Reset *dup() const override {return new Reset(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Reset& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Reset& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::Reset *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Reset*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_RESET_M_H

