//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ddc/message/ResponseNodeInformation.msg.
//

#ifndef __INET_RESPONSENODEINFORMATION_M_H
#define __INET_RESPONSENODEINFORMATION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class ResponseNodeInformation;

}  // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

/**
 * Class generated from <tt>ddc/message/ResponseNodeInformation.msg:12</tt> by opp_msgtool.
 * <pre>
 * class ResponseNodeInformation extends inet::Packet
 * {
 * }
 * </pre>
 */
class ResponseNodeInformation : public ::inet::Packet
{
  protected:

  private:
    void copy(const ResponseNodeInformation& other);

  protected:
    bool operator==(const ResponseNodeInformation&) = delete;

  public:
    ResponseNodeInformation(const char *name=nullptr);
    ResponseNodeInformation(const ResponseNodeInformation& other);
    virtual ~ResponseNodeInformation();
    ResponseNodeInformation& operator=(const ResponseNodeInformation& other);
    virtual ResponseNodeInformation *dup() const override {return new ResponseNodeInformation(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResponseNodeInformation& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResponseNodeInformation& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ResponseNodeInformation *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ResponseNodeInformation*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_RESPONSENODEINFORMATION_M_H

