//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ddc/message/Route.msg.
//

#ifndef __INET_ROUTE_M_H
#define __INET_ROUTE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class Route;

}  // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

/**
 * Class generated from <tt>ddc/message/Route.msg:13</tt> by opp_msgtool.
 * <pre>
 * class Route extends inet::Packet
 * {
 * }
 * </pre>
 */
class Route : public ::inet::Packet
{
  protected:

  private:
    void copy(const Route& other);

  protected:
    bool operator==(const Route&) = delete;

  public:
    Route(const char *name=nullptr);
    Route(const Route& other);
    virtual ~Route();
    Route& operator=(const Route& other);
    virtual Route *dup() const override {return new Route(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Route& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Route& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::Route *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Route*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_ROUTE_M_H

