//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ddc/message/Schedule.msg.
//

#ifndef __INET_SCHEDULE_M_H
#define __INET_SCHEDULE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class Schedule;

}  // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

/**
 * Class generated from <tt>ddc/message/Schedule.msg:13</tt> by opp_msgtool.
 * <pre>
 * class Schedule extends inet::Packet
 * {
 * }
 * </pre>
 */
class Schedule : public ::inet::Packet
{
  protected:

  private:
    void copy(const Schedule& other);

  protected:
    bool operator==(const Schedule&) = delete;

  public:
    Schedule(const char *name=nullptr);
    Schedule(const Schedule& other);
    virtual ~Schedule();
    Schedule& operator=(const Schedule& other);
    virtual Schedule *dup() const override {return new Schedule(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Schedule& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Schedule& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::Schedule *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Schedule*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_SCHEDULE_M_H

